language: bash
services: docker
dist: xenial

env:
  global:
    - BIN_DIR=$HOME/bashbrew_bin/.cache/

cache:
  directories:
  - $BIN_DIR
  - $HOME/user/.cache/bashbrew
  - $HOME/user/docker/official-images/library

jobs:
  include:
    - stage: build
      install:
        - wget -P $BIN_DIR https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
        - chmod +x $BIN_DIR/bashbrew-amd64
        - export PATH=$PATH:$BIN_DIR
      script:
        - ./generate-stackbrew-library.sh > cartridge
        - bashbrew-amd64 build ./cartridge

    - stage: push
      if: (branch = fix-travis-ci) AND NOT (type = pull_request)
      install:
        - export PATH=$PATH:$BIN_DIR
      script:
        - echo "$MY_DOCKER_PASSWORD" | docker login -u "$MY_DOCKER_USERNAME" --password-stdin
        - bashbrew-amd64 tag --target-namespace vanyarock01 ./cartridge
        - bashbrew-amd64 --namespace vanyarock01 push ./cartridge



