language: bash
services: docker
dist: xenial

env:
  global:
    - CACHE_DIR=$HOME/cache_dir/

cache:
  directories:
  - $CACHE_DIR
  - /home/user/.cache/bashbrew/
  # - home/user/.config/bashbrew

jobs:
  include:
    - stage: build
      install:
        - wget -P $CACHE_DIR https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
        - chmod +x $CACHE_DIR/bashbrew-amd64
        - export PATH=$PATH:$CACHE_DIR
      script:
        - ./generate-stackbrew-library.sh > $CACHE_DIR/cartridge
        - bashbrew-amd64 build $CACHE_DIR/cartridge

    - stage: push
      if: (branch = fix-travis-ci) AND NOT (type = pull_request)
      install:
        - export PATH=$PATH:$CACHE_DIR
      script:
        - echo "$MY_DOCKER_PASSWORD" | docker login --username "$MY_DOCKER_USERNAME" --password-stdin
        - bashbrew-amd64 tag --target-namespace vanyarock01 $CACHE_DIR/cartridge
        - bashbrew-amd64 --namespace vanyarock01 push $CACHE_DIR/cartridge



