language: bash
services: docker
dist: xenial

before_script:
  - wget https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
  - chmod +x bashbrew-amd64

script:
  - ./generate-stackbrew-library.sh > cartridge
  - ./bashbrew-amd64 build ./cartridge

deploy:
  provider: script
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - ./bashbrew-amd64 tag --target-namespace tarantool ./cartridge
    - ./bashbrew-amd64 --namespace tarantool push ./cartridge
  on:
    branch: master
