language: bash
services: docker
dist: xenial

env:
  global:
    - BIN_DIR=$HOME/bin_cache
    - DOCKER_DIR=$HOME/docker_cache
    - NAMESPACE=vanyarock01

cache:
  bundler: true
  directories:
  - $BIN_DIR
  - $DOCKER_DIR
  - /var/lib/docker/

jobs:
  include:
    - stage: build
      install:
        - wget -P $BIN_DIR https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
        - chmod +x $BIN_DIR/bashbrew-amd64
        - export PATH=$PATH:$BIN_DIR
      script:
        - ./generate-stackbrew-library.sh > $BIN_DIR/cartridge
        - bashbrew-amd64 build $BIN_DIR/cartridge
        - mkdir -p $DOCKER_DIR
        - docker save $(docker images | grep $NAMESPACE/cartridge | awk '{print $1 ":" $2}') | gzip -2 > $DOCKER_DIR/images_cache.tar.gz

    - stage: push
      if: (branch = fix-travis-ci) AND NOT (type = pull_request)
      install:
        - export PATH=$PATH:$BIN_DIR
        - docker import $DOCKER_DIR/images_cache.tar.gz
        - docker images
      script:
        - echo "$MY_DOCKER_PASSWORD" | docker login --username "$MY_DOCKER_USERNAME" --password-stdin
        - bashbrew-amd64 tag --target-namespace $NAMESPACE $BIN_DIR/cartridge
        - bashbrew-amd64 --namespace $NAMESPACE push $BIN_DIR/cartridge



