language: bash
services: docker
dist: xenial

env:
  global:
    - NAMESPACE=tarantool

install:
  - wget https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/bashbrew-amd64
  - chmod +x bashbrew-amd64
  - ./generate-stackbrew-library.sh > cartridge
  - ./bashbrew-amd64 build ./cartridge

script:
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
      echo "$MY_DOCKER_PASSWORD" | docker login --username "$MY_DOCKER_USERNAME" --password-stdin
      ./bashbrew-amd64 tag --target-namespace $NAMESPACE ./cartridge
      ./bashbrew-amd64 --namespace $NAMESPACE push ./cartridge
    fi